all_roads = [
    "Alston Road",
    "Appleby Road",
    "Ardmore Road",
    "Armadale Road",
    "Banbury Avenue",
    "Bexley Avenue",
    "Bibbys Road",
    "Bispham Road",
    "Blackfen Place",
    "Bluebell Close",
    "Bracken Way",
    "Broderick Avenue",
    "Bromley Close",
    "Brough Avenue",
    "Canada Crescent",
    "Chelsea Avenue",
    "Chestnut Close",
    "Chive Close",
    "Collins Avenue",
    "Coriander Close",
    "Corrib Road",
    "Cotswold Road",
    "Courtfield Avenue",
    "Danson Gardens",
    "Devonshire Road",
    "Dudley Avenue",
    "Edmonton Place",
    "Elmridge Crescent",
    "Essex Place",
    "Fennel Close",
    "Fitzroy Road",
    "Galway Avenue",
    "Goodwood Avenue",
    "Greenbanks",
    "Gresley Place",
    "Hayfield Avenue",
    "Headfort Close",
    "Hetherington Place",
    "Hilstone Lane",
    "Holcombe Road",
    "Holyoake Avenue",
    "Hughes Grove",
    "Hurstwood Drive",
    "Inver Road",
    "Jersey Avenue",
    "Kylemore Avenue",
    "Langdon Way",
    "Leys Road",
    "Lime Grove",
    "Limerick Road",
    "Linden Place",
    "Lorne Road",
    "Low Moor Road",
    "Ludlow Grove",
    "Maurice Grove",
    "Maxwell Grove",
    "Meadow Close",
    "Meadow Crescent",
    "Mexford Avenue",
    "Moor Park Avenue",
    "Morston Avenue",
    "Normandie Avenue",
    "Parsley Close",
    "Pearl Avenue",
    "Penhill Close",
    "Quebec Avenue",
    "Rathmore Gardens",
    "Raymond Avenue",
    "Regency Gardens",
    "Runcorn Avenue",
    "Sage Close",
    "Salcombe Avenue",
    "Salmesbury Avenue",
    "Seattle Avenue",
    "Sidney Avenue",
    "St Michael's Road",
    "Stopford Avenue",
    "Summerwood Close",
    "Tarragon Drive",
    "Teesdale Avenue",
    "Thyme Close",
    "Toronto Avenue",
    "Tower View",
    "Tyrone Avenue",
    "Valentia Road",
    "Warbreck Hill Road",
    "Warley Road",
    "Washington Avenue",
    "Washington Court",
    "Waterside"
]

leafletted = [
    "Alston Road",
    "Bispham Road",
    "Broderick Avenue",
    "Brough Avenue",
    "Chive Close",
    "Coriander Close",
    "Elmridge Crescent",
    "Essex Place",
    "Fennel Close",
    "Fitzroy Road",
    "Greenbanks",
    "Holyoake Avenue",
    "Linden Place",
    "Low Moor Road",
    "Ludlow Grove",
    "Meadow Crescent",
    "Parsley Close",
    "Runcorn Avenue",
    "Sage Close",
    "Salcombe Avenue",
    "Salmesbury Avenue",
    "Seattle Avenue",
    "Tarragon Drive",
    "Thyme Close",
    "Washington Avenue",
    "Washington Court"
]

leafletted_set = set(leafletted)
remaining = [road for road in all_roads if road not in leafletted_set]

print(f"Leafletting Progress")
print(f"===================")
print(f"Roads completed: {len(leafletted)}")
print(f"Roads remaining: {len(remaining)}")
progress = len(leafletted) / len(all_roads) * 100
print(f"Progress: {progress:.1f}%")
print()
print(f"Roads Still Needing Leaflets ({len(remaining)})")
print("=" * 40)
for road in remaining:
    print(road)
